// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCleanup() {
  return window['go']['services']['CleanupService']['CancelCleanup']();
}

export function DetectStateFiles(arg1) {
  return window['go']['services']['CleanupService']['DetectStateFiles'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['CleanupService']['SetContext'](arg1);
}

export function StartCleanup(arg1) {
  return window['go']['services']['CleanupService']['StartCleanup'](arg1);
}
