// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CancelCleanup():Promise<void>;

export function DetectStateFiles(arg1:string):Promise<Array<services.StateFileInfo>>;

export function StartCleanup(arg1:services.CleanupRequest):Promise<void>;
