// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCopy() {
  return window['go']['services']['CopyService']['CancelCopy']();
}

export function ChooseDestination() {
  return window['go']['services']['CopyService']['ChooseDestination']();
}

export function SetConfig(arg1) {
  return window['go']['services']['CopyService']['SetConfig'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['CopyService']['SetContext'](arg1);
}

export function StartBackup(arg1, arg2, arg3) {
  return window['go']['services']['CopyService']['StartBackup'](arg1, arg2, arg3);
}
