// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CancelCopy():Promise<void>;

export function ChooseDestination():Promise<string>;

export function SetConfig(arg1:services.ConfigService):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartBackup(arg1:string,arg2:string,arg3:string):Promise<string>;
