// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceStatus() {
  return window['go']['services']['DeviceService']['GetDeviceStatus']();
}

export function SetContext(arg1) {
  return window['go']['services']['DeviceService']['SetContext'](arg1);
}

export function StartPolling(arg1) {
  return window['go']['services']['DeviceService']['StartPolling'](arg1);
}
