// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceStatus() {
  return window['go']['services']['DeviceService']['GetDeviceStatus']();
}
