// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob() {
  return window['go']['services']['JobManager']['CancelJob']();
}

export function CompleteJob(arg1) {
  return window['go']['services']['JobManager']['CompleteJob'](arg1);
}

export function GetJobStatus() {
  return window['go']['services']['JobManager']['GetJobStatus']();
}

export function SetContext(arg1) {
  return window['go']['services']['JobManager']['SetContext'](arg1);
}

export function SetProcessPID(arg1, arg2) {
  return window['go']['services']['JobManager']['SetProcessPID'](arg1, arg2);
}

export function StartJob(arg1) {
  return window['go']['services']['JobManager']['StartJob'](arg1);
}
