// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob() {
  return window['go']['services']['JobManager']['CancelJob']();
}

export function CancelTask(arg1) {
  return window['go']['services']['JobManager']['CancelTask'](arg1);
}

export function GetActiveTask() {
  return window['go']['services']['JobManager']['GetActiveTask']();
}

export function GetJobStatus() {
  return window['go']['services']['JobManager']['GetJobStatus']();
}

export function GetTask(arg1) {
  return window['go']['services']['JobManager']['GetTask'](arg1);
}

export function ListTasks() {
  return window['go']['services']['JobManager']['ListTasks']();
}

export function SetContext(arg1) {
  return window['go']['services']['JobManager']['SetContext'](arg1);
}

export function SetProcessPID(arg1, arg2) {
  return window['go']['services']['JobManager']['SetProcessPID'](arg1, arg2);
}
