// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CancelJob():Promise<void>;

export function CompleteJob(arg1:boolean):Promise<void>;

export function GetJobStatus():Promise<services.JobInfo>;

export function SetProcessPID(arg1:number,arg2:number):Promise<void>;

export function StartJob(arg1:string):Promise<string>;
