// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CancelJob():Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function EmitLogLine(arg1:string,arg2:string):Promise<void>;

export function GetActiveTask():Promise<services.TaskSnapshot>;

export function GetJobStatus():Promise<services.JobInfo>;

export function GetTask(arg1:string):Promise<services.TaskSnapshot>;

export function ListTasks():Promise<Array<services.TaskSnapshot>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetProcessPID(arg1:number,arg2:number):Promise<void>;
