// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportDiagnostics(arg1) {
  return window['go']['services']['LogService']['ExportDiagnostics'](arg1);
}

export function GetRecentLogs(arg1) {
  return window['go']['services']['LogService']['GetRecentLogs'](arg1);
}
