// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function ExportDiagnostics(arg1:string):Promise<void>;

export function GetRecentLogs(arg1:number):Promise<Array<services.LogEntry>>;

export function SetContext(arg1:context.Context):Promise<void>;
