// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetPrereqReport():Promise<services.PrereqReport>;

export function RefreshNow():Promise<services.PrereqReport>;

export function SetContext(arg1:context.Context):Promise<void>;
