// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPrereqReport() {
  return window['go']['services']['PrereqService']['GetPrereqReport']();
}

export function RefreshNow() {
  return window['go']['services']['PrereqService']['RefreshNow']();
}
