// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenPath(arg1) {
  return window['go']['services']['SystemService']['OpenPath'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['SystemService']['SetContext'](arg1);
}
