// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CancelVerify():Promise<void>;

export function StartVerify(arg1:services.VerifyRequest):Promise<void>;
