// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelVerify() {
  return window['go']['services']['VerifyService']['CancelVerify']();
}

export function SetContext(arg1) {
  return window['go']['services']['VerifyService']['SetContext'](arg1);
}

export function StartVerify(arg1) {
  return window['go']['services']['VerifyService']['StartVerify'](arg1);
}
